apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: online-event-booking
data:
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "userdb"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  JWT_SECRET: "your_jwt_secret"
  NODE_ENV: "production"
