apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: online-event-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 22i1351/notification-service:latest
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: DATABASE_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/eventbooking"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: online-event-booking
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
